[features]
seeds = false
skip-lint = false
[programs.localnet]
counter = "<PUT_GENERATED_PROGRAM_ID_HERE>"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/*.ts"